### ISSUE TITLE
ESFNet

### ISSUE THREAD

**Issue by deepseek** [backtime92/CRAFT-Reimplementation#10]
@backtime92 
After doing **a lot of testing**, I found [ESFNet](https://github.com/mrluin/ESFNet-Pytorch) to have great potential at text-detection tasks.

ESFNet have:
- Very fast Training `4 hours`.
- Very fast Inferencing `100 -142 fps`
- Very little parameters `0.09 - 0.177 M Parameters`
- Very good IoU `82 - 85`

The original implementation by the developer is in PyTorch: [**`source at github`**](https://github.com/mrluin/ESFNet-Pytorch) , [**`Paper.`**](https://arxiv.org/pdf/1903.12337.pdf)

I hope that you really consider ESFNet,
Waiting for your reply.

**Comment by backtime92** [comment]
@deepseek ok,It's on my mind. But  I am focusing on settling the proble mentioned in README. And the new code will be released. The next I will train the model with EfficientNet. Or I think you can have a try to train the model with EfficientNet.
