### ISSUE TITLE
Current result

### ISSUE THREAD

**Issue by lianqing11** [backtime92/CRAFT-Reimplementation#13]
Hi author, have you get a better result with the new dataloader?

**Comment by backtime92** [comment]
@lianqing11 yes, I have got the result in IC15 for 81.41% and  MLT for 91.3%, and now I am training the model. So it's not the last result, I will release the pre-trained model after 2~3days. I have released the new code, you can try to train it. I think the gaussian hyper-parameters for 0.3,0.15 is best. Maybe you can get the same result as me.

**Comment by lianqing11** [comment]
Thanks for your reply. I will try it.
