### ISSUE TITLE
the format of training data

### ISSUE THREAD

**Issue by Jlpz** [backtime92/CRAFT-Reimplementation#16]
hi, this is a good job. But i want to know the format of training data, word-level or character-level bounding-boxes? thank you.

**Comment by backtime92** [comment]
@Jlpz For IC13, IC15, IC17, there is only world-level, but  IC13 with top-left and bottom-right annotation. IC15,IC17 with four point annotaion, top-left, top-right, bottom-right, bottom-left. And Syndata include character-level annotation.

**Comment by Jlpz** [comment]
> @Jlpz For IC13, IC15, IC17, there is only world-level, but IC13 with top-left and bottom-right annotation. IC15,IC17 with four point annotaion, top-left, top-right, bottom-right, bottom-left. And Syndata include character-level annotation.

ok, thank you. I means the format of training data in CRAFT_Reimplementation, word-level or character-level bounding-boxes? I try to train the model, and i used the word-level bounding-boxes. In addition, i get some warning, as follows:
![TIM截图20190929201919](https://user-images.githubusercontent.com/22097967/65832484-f282c780-e2f6-11e9-87e1-f469c4d2d63f.png)

And i try to address some errors. I found "t=None", it is the cause of this error. as follows:
![TIM截图20190929202550](https://user-images.githubusercontent.com/22097967/65832525-8e143800-e2f7-11e9-8de4-e8a114f4cfef.png)
best,

**Comment by Jlpz** [comment]
> @Jlpz For IC13, IC15, IC17, there is only world-level, but IC13 with top-left and bottom-right annotation. IC15,IC17 with four point annotaion, top-left, top-right, bottom-right, bottom-left. And Syndata include character-level annotation.

@backtime92 ok, thank you. I means the format of training data in CRAFT-Reimplementation, word-level or character-level bounding-boxes? I try to train a model, i have used the word-level bounding-boxes of Syndata. But i get some warning, as follows:
![TIM截图20190929201919](https://user-images.githubusercontent.com/22097967/65832609-95881100-e2f8-11e9-90fa-ead9cb6745cf.png)

And i try to address some errors, as follows. I found "t=None", it is the cause of this error.
![TIM截图20190929202550](https://user-images.githubusercontent.com/22097967/65832627-d97b1600-e2f8-11e9-92cb-a7d7fc7f970c.png)
best,

**Comment by backtime92** [comment]
@Jlpz I met the warning, because the are width or height < 1. And the reason of the error is some word label annotation is empty. Weak supervision supports for word-level.
