### ISSUE TITLE
LinkRefiner

### ISSUE THREAD

**Issue by deepseek** [backtime92/CRAFT-Reimplementation#19]
@backtime92 
clovaai just released the LinkRefiner code clovaai/CRAFT-pytorch@3cd65f5 better you implement it, along with option to train .
So that we can detect text-lines

**Comment by backtime92** [comment]
@deepseek yes, I try the model, but I found it good enough. Now I have writed a new post-processing method for Chinesedata.

**Comment by xwtian** [comment]
do you have a plan to release the code about training linkRefiner?

**Comment by deepseek** [comment]
@backtime92 did you consider adding LinkRefiner and allow training in the new code?

**Comment by backtime92** [comment]
No
