### ISSUE TITLE
Why `copyStateDict`?

### ISSUE THREAD

**Issue by ThisIsIsaac** [backtime92/CRAFT-Reimplementation#32]
Just out of curiosity, is there a reason why you make a copy of `state_dict` before loading to `CRAFT.load_state_dict` with `copyStateDict`?

**Comment by backtime92** [comment]
@ThisIsIsaac I do not know what you said about the code, can you show it for me?

**Comment by ThisIsIsaac** [comment]
```python
def copyStateDict(state_dict):
    if list(state_dict.keys())[0].startswith("module"):
        start_idx = 1
    else:
        start_idx = 0
    new_state_dict = OrderedDict()
    for k, v in state_dict.items():
        name = ".".join(k.split(".")[start_idx:])
        new_state_dict[name] = v
    return new_state_dict
```

I'm assuming this is to be able to load models that were saved in with `DataParallel` without `DataParallel`.

**Comment by backtime92** [comment]
@ThisIsIsaac Yes，this is the repetitive one. Sorry for that, it is for test  and I forget delete it.

**Comment by ThisIsIsaac** [comment]
@backtime92 Thanks for the answer. I just wanted to make sure I'm not messing up anything. Crystal clear now
