### ISSUE TITLE
can't load `Syndata.pth`: `load_state_dict Missing Keys`

### ISSUE THREAD

**Issue by ThisIsIsaac** [backtime92/CRAFT-Reimplementation#33]
~~How is `Syndata.pth` different from `vgg16_bn-6c64b313.pth`? My guess is `vgg16_bn-6c64b313.pth` is just fro `vgg16` and `Syndata.pth` is for the rest?~~

when I use `Syndata.pth` in `vgg16_bn.py`, I get error: `load_state_dict Missing keys ...`
but when I use `vgg16_bn-6c64b313.pth`, the model load properly.

1. is `Syndata.pth` for the same model as `vgg16_bn-6c64b313.pth`?
2. Why am I getting this bug?

**Comment by backtime92** [comment]
@ThisIsIsaac the syndata.pth is for the CRAFT model parameters, and the vgg16_bn-6c64b313.pth is for the vgg16 with bn model parameters. There are different.

**Comment by ThisIsIsaac** [comment]
Thanks for the answer. A couple follow-up questions:

1. Why do you freeze `CRAFT`'s weight in `trainic15data.py`?
2. What data is `vgg16_bn-6c64b313.pth` trained on?
