### ISSUE TITLE
What languages were included in SynthText? 

### ISSUE THREAD

**Issue by ThisIsIsaac** [backtime92/CRAFT-Reimplementation#37]
1. What languages were included in SynthText? 
2. Was there any word that was laid our vertically (like for traditional Chinese language)?

**Comment by backtime92** [comment]
@ThisIsIsaac 
1. What languages were included in SynthText?
A：it's just English character or word(Syndata). 
2.Was there any word that was laid our vertically (like for traditional Chinese language)?
A:Yes, there are some vertical word but not many(MLT data).
