### ISSUE TITLE
python test.py result is empty

### ISSUE THREAD

**Issue by deepseek** [backtime92/CRAFT-Reimplementation#4]
@backtime92 When running:
`python test.py --trained_model ./weights/CRAFT_90.pth --test_folder ./test`

the result folder is empty, nothing is shown

**Comment by backtime92** [comment]
@deepseek There are no detection boxes or no detection file like .jpg image or .txt file

**Comment by deepseek** [comment]
what do you mean?? I placed alot of .jpg files in ./test

**Comment by backtime92** [comment]
Are you come from China?  add wechat?

**Comment by backtime92** [comment]
@deepseek I test it now , please wati for a moment

**Comment by backtime92** [comment]
@deepseek I jsut test it and it's normal, so I think there is some wrong with your code or maybe others

**Comment by deepseek** [comment]
nope, I kept testing and changing test.py, but still empty result

**Comment by backtime92** [comment]
@deepseek You can test with autor's pre-trained model .pth to verify your result

**Comment by cong235** [comment]
@deepseek please do this follow:
Step1: Edit line 61 and 63 with your link input and output folder image
Step3: add this line in the end of file:
test("./weights/CRAFT_90.pth")
p/s: other way, you can get the code test from author and use that for testing.

@backtime92 Maybe you forgot write the main function for running code.

**Comment by backtime92** [comment]
yes , I changed the author's test.py. You could use the autor's test.py for test. I make the test.py with a function which can do test in training stage.

**Comment by backtime92** [comment]
@deepseek @cong235 yes , I changed the author's test.py. You could use the autor's test.py for test. I make the test.py with a function which can do test in training stage.

**Comment by deepseek** [comment]
Please note that the original author's test.py works fine. 

When I modify your test.py script an error shows when running.
When using your test.py
```
(final) home@home-desktop:~/programs/CRAFT-Reimplementation-master$ python test.py --trained_model ./weights/CRAFT_90.pth --test_folder ./test
Traceback (most recent call last):
  File "test.py", line 115, in <module>
    net = CRAFT()     # initialize
  File "/home/home/programs/CRAFT-Reimplementation-master/craft.py", line 42, in __init__
    self.basenet = vgg16_bn(pretrained, freeze)
  File "/home/home/programs/CRAFT-Reimplementation-master/basenet/vgg16_bn.py", line 20, in __init__
    copyStateDict(torch.load(os.path.join(weights_folder, '/data/CRAFT-pytorch/vgg16_bn-6c64b313.pth'))))
  File "/home/home/anaconda3/envs/final/lib/python3.6/site-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/data/CRAFT-pytorch/vgg16_bn-6c64b313.pth'

```

**Comment by josmecedo** [comment]
> Please note that the original author's test.py works fine.
> 
> When I modify your test.py script an error shows when running.
> When using your test.py
> 
> ```
> (final) home@home-desktop:~/programs/CRAFT-Reimplementation-master$ python test.py --trained_model ./weights/CRAFT_90.pth --test_folder ./test
> Traceback (most recent call last):
>   File "test.py", line 115, in <module>
>     net = CRAFT()     # initialize
>   File "/home/home/programs/CRAFT-Reimplementation-master/craft.py", line 42, in __init__
>     self.basenet = vgg16_bn(pretrained, freeze)
>   File "/home/home/programs/CRAFT-Reimplementation-master/basenet/vgg16_bn.py", line 20, in __init__
>     copyStateDict(torch.load(os.path.join(weights_folder, '/data/CRAFT-pytorch/vgg16_bn-6c64b313.pth'))))
>   File "/home/home/anaconda3/envs/final/lib/python3.6/site-packages/torch/serialization.py", line 381, in load
>     f = open(f, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: '/data/CRAFT-pytorch/vgg16_bn-6c64b313.pth'
> ```

I'm having that same problem, the missing weights for vgg16. Did you just download the weights and put them in that folder?
