### ISSUE TITLE
[BUG] Unexpected 'CUDA out of memory'

### ISSUE THREAD

**Issue by LJXLJXLJX** [backtime92/CRAFT-Reimplementation#42]
I tried to run test.py but the error occurred.

> RuntimeError: CUDA out of memory. Tried to allocate 644.00 MiB (GPU 0; 10.92 GiB total capacity; 9.81 GiB already allocated; 567.00 MiB fre; 53.70 MiB cached)

I run the nvdia-smi and I found that the memory is actually sufficient （12GB remain）

How can I fix it?

**Comment by backtime92** [comment]
@LJXLJXLJX it needs 4 gpu.
