### ISSUE TITLE
Bad detection samples

### ISSUE THREAD

**Issue by deepseek** [backtime92/CRAFT-Reimplementation#5]
@backtime92 
is the `Bad detection samples` related to https://github.com/clovaai/CRAFT-pytorch/pull/36
?

**Comment by backtime92** [comment]
@deepseek Maybe not, I think the author used different hyper-parameters to generate gaussian for region score and affinity score map which can split the gaussian map well. And the bad detection samples for big word may be due to the random crop algorithm which not suits for this paper method.
