### ISSUE TITLE
Gaussian map have some problem with my model

### ISSUE THREAD

**Issue by dont32** [backtime92/CRAFT-Reimplementation#55]
I ported your code to mxnet but when try to trained a model syntext. Gaussian map have some problem with my model.Right of page is lose. @backtime92 can you give some advice ?
![_mask](https://user-images.githubusercontent.com/23291353/81465631-84d83b80-91f5-11ea-87fe-84aee95f7aac.jpg)

**Comment by dont32** [comment]
Data predicted somthing is NAN
[[[[0.02841382 0.01564853]   
   [0.04170848 0.01751898]   
   [0.04774318 0.01982683]   
   ...                       
   [       nan        nan]   
   [       nan        nan]   
   [       nan        nan]]  
                             
  [[0.03000581 0.01689373]   
   [0.04385772 0.02441046]   
   [0.04874859 0.02909794]   
   ...                       
   [       nan        nan]   
   [       nan        nan]   
   [       nan        nan]]  
                             
  [[0.02739267 0.01795962]   
   [0.04255428 0.02428157]   
   [0.04612475 0.02915707]   
   ...                       
   [       nan        nan]   
   [       nan        nan]   
   [       nan        nan]]  
                             
  ...                        
                             
  [[0.03991995 0.02184485]   
   [0.06015404 0.0304684 ]   
   [0.06290139 0.03211661]   
   ...                       
   [       nan        nan]   
   [       nan        nan]   
   [       nan        nan]]  
                             
  [[0.03309158 0.01895588]   
   [0.05485419 0.02265875]   
   [0.05775831 0.02417065]   
   ...                       
   [       nan        nan]   
   [       nan        nan]   
   [       nan        nan]]  
                             
  [[0.01755682 0.01472512]   
   [0.03305354 0.01134156]   
   [0.03661436 0.00940421]   
   ...                       
   [       nan        nan]   
   [       nan        nan]   
   [       nan        nan]]]]
@backtime92

**Comment by woans0104** [comment]
@dont32 How did you solve the problem?

**Comment by bmtuan** [comment]
@dont32 Has this problem been solved? Please show me the solution
