### ISSUE TITLE
Difference in eval score of ic15 pretrained model

### ISSUE THREAD

**Issue by huntu0042** [backtime92/CRAFT-Reimplementation#56]
Thanks for the code and model disclosure.

Test results performed with the IC15 pretrained model are different from those recorded.

I downloaded your ic15 pretrained model from Google Drive. After executing test function, evaluation function was executed.

In 'readme', recall = 76%, precision = 84%,  hmean = 80% for ICDAR2015 dataset.
But the evaluation result I did with the model is recall = 70.5%, precision = 80.3%, hmean = 75.1%.

Why are the results different? Is the model that measured the score different from the model of google drive?

**Comment by backtime92** [comment]
@huntu0042 sorry for the mismatch pretrained model, I will upload the new pretrained model.(ic15 with 0.8226, ic13 with 0.9224)

**Comment by huntu0042** [comment]
ok, thanks for comment!
