### ISSUE TITLE
为何训练过后的模型测试结果全为空，一个检测框都没有

### ISSUE THREAD

**Issue by pingzi5233** [backtime92/CRAFT-Reimplementation#58]
如题，在作者给的synthdata.pth基础上，训练icdar15的数据，如果学习率设很小的值，前两个epoch还会有检测框，慢慢就没有检测框了，变成全空的检测结果，如果学习率调大，第一个epoch直接没有检测结果，请问有人知道为什么吗？

**Comment by zcswdt** [comment]
> 在作者给的synthdata.pth基础上，训练icdar15

请问您完成了训练实验么
