### ISSUE TITLE
loss nan

### ISSUE THREAD

**Issue by woans0104** [backtime92/CRAFT-Reimplementation#87]
I trained with the Synthtext data, and the loss became nan values ​​over 20,000 epochs. Can anyone give me advice on this issue?

3000 0.1077
4000 0.1032 
5000 0.1003
6000 0.0984 
7000 0.0970 
8000 0.0956 
9000 0.0948 
10000 0.0940 
11000 0.0933 
12000 0.0925 
13000 0.0919 
14000 0.0914 
15000 0.0909 
16000 0.0904 
17000 0.0900 
18000 0.0897 
19000 0.0893 
20000 0.0889 
21000 0.0884 
22000 0.0878 
23000 nan 
24000 nan 
25000 nan 
26000 nan 
27000 nan 
28000 nan 
29000 nan 
30000 nan 
31000 nan
32000 nan 
33000 nan 
34000 nan 
35000 nan 
36000 nan 
37000 nan 
38000 nan 
39000 nan 
40000 nan 
41000 nan 
42000 nan 
43000 nan 
44000 nan 
45000 nan 
46000 nan 
47000 nan 
48000 nan 
49000 nan 
50000 nan

**Comment by backtime92** [comment]
非常抱歉一直没有维护这个工程，我会在12月中旬左右给出新的模型和整理后的工程，近期可能会在新得分支陆续更新code。

**Comment by bmtuan** [comment]
@woans0104 How did you solve this problem?
