### ISSUE TITLE
question of  perspective transform

### ISSUE THREAD

**Issue by woans0104** [backtime92/CRAFT-Reimplementation#91]
@backtime92 Thanks for updating the code. I have a few questions.
1. Why is this function necessary to make the size of the character box 1.5 times larger by using enlargebox?

https://github.com/backtime92/CRAFT-Reimplementation/blob/fbaa63aebd61c2b290752102cdef4758891b1fb7/gaussianMap/gaussian.py#L104

2. What is the reason for shifting the box using the variable top_left?
https://github.com/backtime92/CRAFT-Reimplementation/blob/fbaa63aebd61c2b290752102cdef4758891b1fb7/gaussianMap/gaussian.py#L113-L115

**Comment by backtime92** [comment]
1、I asked the author and compared the Gaussian map of the text area after affine transformation in the paper, and found that it was 1.5 larger closer to the map in the paper.
2、referece the opencv demo

**Comment by backtime92** [comment]
Since the weakly supervised training has encountered a little problem, and GPUS is running other experiments, there is no extra for weakly supervised experiment, and I will continue the weakly supervised part of the experiment when the GPUs are free.

**Comment by woans0104** [comment]
But why not apply it to affinity box??

https://github.com/backtime92/CRAFT-Reimplementation/blob/fbaa63aebd61c2b290752102cdef4758891b1fb7/gaussianMap/gaussian.py#L105-L106
