### ISSUE TITLE
question on watershed

### ISSUE THREAD

**Issue by woans0104** [backtime92/CRAFT-Reimplementation#93]
There are many hyperparameters in the watershed.py. Is there a way to find the optimal hyperparameters to make the box close to the model's output?

**Comment by backtime92** [comment]
Of course, the watershed uploaded on github is an old version. I misinformed it. There seems to be a problem with gitignore. You can refer to the watershed algorithm that I have rewritten at present, of course, I may continue to adjust it in the future.

`import cv2
import numpy as np
import Polygon as plg

def mean_crop_img(image, text_len):
    heigh, width = image.shape[:2]
    y1 = 0
    y2 = heigh
    boxes = []
    mean_w = width // text_len
    for i in range(text_len):
        box = [[i*mean_w, y1], [(i+1)*mean_w, y1], [(i+1)*mean_w, y2], [i*mean_w, y2]]
        boxes.append(box)
    return boxes

def get_confidence(real_len, pursedo_len):
    if pursedo_len == 0:
        return 0.
    return float((real_len - min(real_len, abs(real_len - pursedo_len)))) / float(real_len)

def watershed1(image, region_score, text):
    visual = False
    region_score = np.uint8(np.clip(region_score, 0, 1) * 255)
    region_score = cv2.cvtColor(region_score, cv2.COLOR_GRAY2BGR)
    boxes = []
    if len(region_score.shape) == 3:
        gray = cv2.cvtColor(region_score, cv2.COLOR_BGR2GRAY)
    else:
        gray = region_score

    if visual:
        cv2.imshow("gray", gray)

    ret, binary = cv2.threshold(gray, 0.2*np.max(gray), 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    mb = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=2)  # iterations连续两次开操作
    sure_bg = cv2.dilate(mb, kernel, iterations=3)  # 3次膨胀,可以获取到大部分都是背景的区域
    # sure_bg = mb
    if visual:
        cv2.imshow("sure_bg", sure_bg)
        cv2.imshow("gray1", gray)

    ret, sure_fg = cv2.threshold(gray, 0.7 * np.max(gray), 255, cv2.THRESH_BINARY+cv2.THRESH_OTSU)
    sure_fg = cv2.dilate(sure_fg, kernel, iterations=1)  
    if visual:
        cv2.imshow("sure_fg", sure_fg)
    surface_fg = np.uint8(sure_fg)  
    surface_bg = np.uint8(sure_bg)
    unknown = cv2.subtract(surface_bg, surface_fg)

    if visual:
        cv2.imshow("unknown", unknown)
    # 获取maskers,在markers中含有种子区域

    ret, markers = cv2.connectedComponents(surface_fg)
    # 分水岭变换
    markers = markers + 1
    markers[unknown == 255] = 0
    markers = cv2.watershed(region_score, markers=markers)
    region_score[markers == -1] = [0, 0, 255]

    if visual:
        cv2.imshow("water", region_score)

    for i in range(2, np.max(markers) + 1):
        np_contours = np.roll(np.array(np.where(markers == i)), 1, axis=0).transpose().reshape(-1, 2)
        rectangle = cv2.minAreaRect(np_contours)
        box = cv2.boxPoints(rectangle)

        startidx = box.sum(axis=1).argmin()
        box = np.roll(box, 4 - startidx, 0)
        poly = plg.Polygon(box)
        area = poly.area()
        if area < 10:
            continue
        box = np.array(box)
        boxes.append(box)

        if visual:
            cv2.polylines(image, [np.array(box, dtype=np.int) * 2], True, (0, 255, 255), 1)
            cv2.namedWindow("water1", cv2.WINDOW_NORMAL)
            cv2.imshow("water1", image)
            cv2.waitKey(0)

    boxes = np.array(boxes) * 2
    boxes = sorted(boxes, key=lambda item: (item[0][0], item[0][1]))
    confidence = get_confidence(len(text), len(boxes))
    if confidence < 0.5:
        boxes = mean_crop_img(image, len(text))
        confidence = 0.5

    if confidence == 0.0:
        print("confidence: ", confidence)
    return np.array(boxes), confidence`

em...Insert code doesn't seem to work.

**Comment by woans0104** [comment]
thanks :)
