### ISSUE TITLE
question on trainSynth.py result

### ISSUE THREAD

**Issue by woans0104** [backtime92/CRAFT-Reimplementation#95]
I experimented with the updated trainSynth.py, and there was no significant difference in performance from the code before the update. 

Is there any difference between the updated code and before it is different except for the difference in gaussian map generation, transform, and augmentation(update code only random crop)?

And is the performance difference similar only in my experimental results?

**Comment by backtime92** [comment]
There may be some improvement in the weak supervision part. It still needs to wait for some time to experiment. Recently, the work has been busy, and the experiment has temporarily stalled
