### ISSUE TITLE
请问作者在 Synthdata 上训练了多少个epoch？

### ISSUE THREAD

**Issue by Lovegood-1** [backtime92/CRAFT-Reimplementation#97]
我想使用自己的 model 来测试 icdar2015。但是在此之前需要先在合成数据集上训练模型。我想请问作者大佬，您在 synthdata 上训练了多少个epoch？

我看 trainSynth.py 里面训练了1000个epoch，但是这不是太慢了吗？

**Comment by backtime92** [comment]
训练两个epoch就可以了，参照作者在issue里提到的。
